export const MONGODB_BACKEND_URI = process.env.MONGODB_BACKEND_URI
export const MONGODB_DB = process.env.MONGODB_DB
export const MONGODB_CLIENTS_COLLECTION = process.env.MONGODB_CLIENTS_COLLECTION
export const MONGODB_ROUTINES_COLLECTION =
  process.env.MONGODB_ROUTINES_COLLECTION
export const MONGODB_EXERCISES_COLLECTION =
  process.env.MONGODB_EXERCISES_COLLECTION
